name: Build DuyKhanhOS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-common \
            grub-pc-bin \
            grub-efi-amd64-bin \
            grub2-common \
            mtools \
            dosfstools \
            rsync \
            tree

      - name: Build rootfs
        run: |
          chmod +x scripts/build.sh
          sudo ./scripts/build.sh

      - name: Customize rootfs
        run: |
          chmod +x scripts/customize.sh
          sudo ./scripts/customize.sh

      - name: Show boot files
        run: |
          echo "===== rootfs/boot ====="
          sudo ls -lah rootfs/boot

          echo "===== Kernel ====="
          sudo find rootfs/boot -name "vmlinuz-*"

          echo "===== Initrd ====="
          sudo find rootfs/boot -name "initrd.img-*"

      - name: Create SquashFS
        run: |
          sudo mksquashfs rootfs filesystem.squashfs \
            -comp zstd \
            -Xcompression-level 15 \
            -processors $(nproc) \
            -e boot

      - name: Prepare ISO structure
        run: |
          mkdir -p iso/live

          sudo cp filesystem.squashfs iso/live/

          KERNEL=$(sudo find rootfs/boot -name "vmlinuz-*" | head -n1)
          INITRD=$(sudo find rootfs/boot -name "initrd.img-*" | head -n1)

          echo "Kernel=$KERNEL"
          echo "Initrd=$INITRD"

          sudo cp "$KERNEL" iso/live/vmlinuz
          sudo cp "$INITRD" iso/live/initrd.img

      - name: Debug live files
        run: |
          echo "===== iso/live ====="
          ls -lah iso/live

          echo "===== ISO tree ====="
          find iso

      - name: Prepare GRUB
        run: |
          chmod +x scripts/grub.sh
          sudo ./scripts/grub.sh

      - name: Create ISO
        run: |
          chmod +x scripts/make_iso.sh
          sudo ./scripts/make_iso.sh

      - name: Verify output
        run: |
          ls -lah output

      - name: Fix ownership
        run: |
          sudo chown -R $USER:$USER output

      - name: Generate SHA256
        run: |
          cd output
          sha256sum DuyKhanhOS-5.0-final-amd64.iso > sha256sum.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuyKhanhOS-5.0-final-amd64
          path: |
            output/DuyKhanhOS-5.0-final-amd64.iso
            output/sha256sum.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v5.0-final
          name: DuyKhanhOS v5.0-final
          files: |
            output/DuyKhanhOS-5.0-final-amd64.iso
            output/sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
