name: Build DuyKhanhOS

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-common \
            grub-pc-bin \
            grub-efi-amd64-bin \
            grub2-common \
            mtools \
            dosfstools \
            rsync

      - name: Build rootfs
        run: |
          chmod +x scripts/build.sh
          sudo ./scripts/build.sh

      - name: Customize rootfs
        run: |
          chmod +x scripts/customize.sh
          sudo ./scripts/customize.sh

      - name: Show boot files
        run: |
          sudo ls -lah rootfs/boot

      - name: Create SquashFS
        run: |
          sudo mksquashfs rootfs filesystem.squashfs \
            -comp zstd \
            -Xcompression-level 15 \
            -processors $(nproc) \
            -e boot

      - name: Prepare ISO structure
        run: |
          mkdir -p iso/live

          sudo cp filesystem.squashfs iso/live/

          KERNEL=$(sudo ls rootfs/boot/vmlinuz-* | head -n1)
          INITRD=$(sudo ls rootfs/boot/initrd.img-* | head -n1)

          sudo cp "$KERNEL" iso/live/vmlinuz
          sudo cp "$INITRD" iso/live/initrd.img

      - name: Prepare GRUB files
        run: |
          chmod +x scripts/grub.sh
          sudo ./scripts/grub.sh

      - name: Create ISO
        run: |
          chmod +x scripts/make_iso.sh
          sudo ./scripts/make_iso.sh

      - name: Fix ownership
        run: |
          sudo chown -R $USER:$USER output

      - name: Generate SHA256
        run: |
          sha256sum output/DuyKhanhOS-5.0-final-amd64.iso \
            > output/sha256sum.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuyKhanhOS-5.0-final-amd64
          path: |
            output/DuyKhanhOS-5.0-final-amd64.iso
            output/sha256sum.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v5.0-final
          name: DuyKhanhOS v5.0-final
          files: |
            output/DuyKhanhOS-5.0-final-amd64.iso
            output/sha256sum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
